---
- name: Installing MySQL 8.0
  hosts: vagrants
  vars:
    root_user: root
    mysql_user: shahrukh
    mysql_password: shahrukh@123
    db_name: wordpress
    unix_socket: /var/run/mysqld/mysqld.sock 
  become: true
  tasks:
   - apt: update_cache=yes

   - name: Downloading MySQL 8.0 Repo
     get_url:
        url: https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
        dest: /home/vagrant/

   - name: Installing MYSQL Repo
     apt:
       deb: /home/vagrant/mysql-apt-config_0.8.12-1_all.deb
       state: present

   - name: Installing Mysql-Server
     become: yes
     apt:
       name: mysql-server
       state: present 

  #  - name: Installing pip 
  #    apt:
  #       name: python3-pip
  #       state: present

  #  - name: Making sure pymysql is present
  #    pip:
  #       name: pymysql
  #       state: present

  #  - name: Setting up MySQL root password
  #    mysql_user:
  #         login_host: 'localhost'
  #         login_user: '{{ root_user }}'
  #         login_unix_socket: '{{ unix_socket }}'
  #         login_password: "{{ mysql_password }}"
  #         name: '{{ root_user }}'
  #         password: "{{ mysql_password }}"
  #         state: present
  #         priv: '*.*:ALL,GRANT'
         
  #  - name: Setting up MySQL user password
  #    mysql_user:
  #         name: '{{ mysql_user }}'
  #         password: "{{ mysql_password }}"
  #         host: '%'
  #         login_unix_socket: '{{ unix_socket }}'
  #         login_user: '{{ root_user }}'
  #         login_password: "{{ mysql_password }}"
  #         priv: "{{ db_name }}.{{ mysql_user }}:ALL,GRANT"

  #  - name: Creating a Database for wordpress
  #    mysql_db:
  #         name: "{{ db_name }}"
  #         state: present
  #         login_unix_socket: '{{ unix_socket }}'
  #         login_user: '{{ root_user }}'
  #         login_password: "{{ mysql_password }}"
