---
- name: Installing PHP Version 7.2
  hosts: vagrants
  become: yes
  tasks:
   - apt: update_cache=yes
   
   - name: Installing Apache2
     apt:
       name: apache2
       state: present

   - name: Installing Software Common Properties
     apt: 
       name: software-properties-common

   - name: Adding Ondrej PPA
     apt_repository: 
       repo: ppa:ondrej/php
       update_cache: yes 
   - name: Installing PHP 7.2
     apt:
       name: php7.2
       state: present

   - name: Installing require PHP Packages
     apt:
       pkg:
         - libapache2-mod-php7.2
         - php7.2-common
         - php7.2-curl
         - php7.2-mbstring
         - php7.2-xmlrpc
         - php7.2-mysql
         - php7.2-mysqlnd
         - php7.2-opcache
         - php7.2-dev
         - php7.2-gd
         - php7.2-xml
         - php7.2-intl
         - php7.2-ldap
         - php7.2-imagick
         - php7.2-cli
         - php7.2-zip
         - php7.2-bcmath 
         - php7.2-fpm
         - php7.2-soap
         - php7.2-json
         - php7.2-gmp
         - php7.2-dom
         - php7.2-mcrypt
         - php7.2-iconv
         - php7.2-xsl
         - php7.2-ctype
         - php7.2-pdo
         - php7.2-bz2
         - php7.2-calendar
         - php7.2-fileinfo
         - php7.2-tokenizer
         - php7.2-xmlwriter
         - php7.2-xmlreader
         - php7.2-phar
       state: present

   - name: Enabling Apache Module for FASTCGI
     apache2_module:
        name: "{{ item }}"
        state: present
     with_items:
          - actions
          - alias
          - proxy_fcgi
          - rewrite
     notify: 
          - Check Status of Apache2

  handlers:
   - name: Check Status of Apache2
     service: 
        name: apache2
        state: restarted  