---
- name: Installing PHP Version 7.3
  hosts: vagrants
  become: yes
  tasks:
   - apt: update_cache=yes
   
   - name: Installing Apache2
     apt:
       name: apache2
       state: present

   - name: Check Status of Apache2
     service:
       name: apache2
       state: started

   - name: Installing Software Common Properties
     apt: 
       name: software-properties-common

   - name: Adding Ondrej PPA
     apt_repository: 
       repo: ppa:ondrej/php
       update_cache: yes 
   - name: Installing PHP 7.3
     apt:
       name: php7.3
       state: present

   - name: Installing require PHP Packages
     apt:
       pkg:
         - libapache2-mod-php7.3
         - php7.3-common
         - php7.3-curl
         - php7.3-mbstring
         - php7.3-xmlrpc
         - php7.3-mysql
         - php7.3-mysqlnd
         - php7.3-opcache
         - php7.3-dev
         - php7.3-gd
         - php7.3-xml
         - php7.3-intl
         - php7.3-ldap
         - php7.3-imagick
         - php7.3-cli
         - php7.3-zip
         - php7.3-bcmath 
         - php7.3-fpm
         - php7.3-soap
         - php7.3-json
         - php7.3-gmp
         - php7.3-dom
         - php7.3-mcrypt
         - php7.3-iconv
         - php7.3-xsl
         - php7.3-ctype
         - php7.3-pdo
         - php7.3-bz2
         - php7.3-calendar
         - php7.3-fileinfo
         - php7.3-tokenizer
         - php7.3-xmlwriter
         - php7.3-xmlreader
         - php7.3-phar
       state: present

   - name: Enabling Apache Module for FASTCGI
     apache2_module:
        name: "{{ item }}"
        state: present
     with_items:
          - actions
          - alias
          - proxy_fcgi
          - rewrite
     notify: Check Status of Apache2

  handlers:
   - name: Check Status of Apache2
     service: 
        name: apache2
        state: restarted  